# Generated by Django 3.0.7 on 2020-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.EmailField(max_length=254)),
                ('sales', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('landline', models.CharField(max_length=15)),
                ('facebook_link', models.CharField(max_length=250)),
                ('linkedin_link', models.CharField(max_length=250)),
                ('adderess', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
